#!/bin/bash
GREEN="\e[32m"
RESET="\e[0m"
git add .
read -p 'Enter commit message: ' MESSAGE  
echo 'Running git commit'
git commit -m "$MESSAGE"
echo -e '${GREEN}Commit Finished${RESET}'
echo 'Pushing to Repo'
git push origin main
echo -e '${GREEN}Done! Commit finished${RESET}'

